name: wok
favicon: null
layout_spectrum: 0.7123547855298966
typography_spectrum: 0.5503072480205446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9782000789418817
  lightness: 0.010672258213162422
  saturation: 0.575187343172729
  rhythmicContrast: 0.49930032528936863
purpose: []
